"""Plain-language methods text for the app and technical documentation."""

METHODS_PARAGRAPHS: tuple[str, ...] = (
    "This application supports **illustrative what-if planning** for maternal mortality "
    "in the WHO African Region. The primary outcome is the **maternal mortality ratio (MMR)**—"
    "maternal deaths per 100,000 live births—using publicly reported country-year estimates "
    "(UN Maternal Mortality Estimation Inter-Agency Group series via the World Bank). Users "
    "adjust indicators grouped into health system, reproductive, disease, socioeconomic, "
    "infrastructure, governance and data, and emergency or shock domains, then compare a "
    "scenario to the country's latest observed MMR. The tool is designed for dialogue and "
    "priority-setting; it does **not** estimate causal programme impact or replace national "
    "surveillance and evaluation.",
    "The **data layer** builds a harmonised country-year panel (approximately 2000–2023) for "
    "WHO AFRO member states. Core series are downloaded from the **World Bank Open Data API**, "
    "including MMR, skilled birth attendance, fertility and adolescent fertility, modern "
    "contraceptive prevalence, **ANC4 coverage** (`SP.DYN.4ANTE.ZS`), HIV prevalence, malaria "
    "incidence, anaemia in women of reproductive age, poverty, literacy, rural population share, "
    "and **domestic general government health expenditure as a share of GDP** "
    "(`SH.XPD.GHED.GD.ZS`). Where available, additional maternal and health-workforce indicators "
    "are merged from the **WHO Global Health Observatory (OData)** and **UNICEF SDMX** "
    "(institutional delivery and caesarean section). Indicators are outer-joined on ISO3 and year, "
    "then sparse gaps are filled using within-country forward/backward propagation and regional "
    "medians by year so the panel can be used for modelling.",
    "Several requested variables are **not available as consistent open annual series** for all "
    "AFRO countries (for example emergency obstetric care coverage, referral efficiency, travel "
    "time to facilities from GIS models, conflict intensity from ACLED, or flood events from "
    "EM-DAT). For demonstration, these are supplemented with **realistic synthetic trajectories** "
    "(`src/synthetic_data.py`): bounded random walks with small annual drift and deterministic "
    "seeding per country and variable. Synthetic values are applied **only after** authoritative "
    "API data are merged, so observed World Bank, WHO, or UNICEF values always take precedence. "
    "National systems (DHIS2, HMIS, CRVS, facility assessments) should replace synthetic series "
    "when the application is adapted for country use.",
    "A central modelling rule is **indicator directionality**. Each predictor is classified as "
    "either **protective** (higher values reflect better conditions and are expected to be "
    "associated with **lower** MMR) or a **risk factor** (higher values reflect worse conditions "
    "and are expected to be associated with **higher** MMR). Examples of protective indicators "
    "include **ANC4 coverage**, skilled birth attendance, facility delivery, contraceptive "
    "prevalence, literacy, health workforce density, and **government health expenditure (% of "
    "GDP)**—when a user moves these sliders **up**, the model is structured so projected MMR "
    "**falls**. Examples of risk factors include fertility rate, poverty, HIV and malaria burden, "
    "travel time to facilities, and shock indices—moving these **up** raises projected MMR unless "
    "the indicator is one where lower raw values are better (e.g. reducing poverty lowers MMR). "
    "This mapping is stored in `FEATURE_TO_RISK_MULTIPLIER` in `src/constants.py`.",
    "Technically, raw indicators are converted to a **risk-oriented scale** before prediction: "
    "for protective variables the value is multiplied by −1 so that, in model space, **higher "
    "always means higher risk (worse)**. The engine then fits an **additive monotonic model** on "
    "log(MMR): each indicator receives a **non-negative coefficient** fitted from its univariate "
    "relationship with log(MMR) across the panel, which prevents the joint regression from "
    "zeroing out correlated inputs (a problem that previously made sliders appear ineffective). "
    "Coefficients are shrunk slightly for panel fit, then **scenario sensitivity** is calibrated "
    "so that plausible single-lever moves (e.g. +15 percentage points skilled birth attendance) "
    "produce visible but not extreme MMR shifts at country level.",
    "For **country scenarios**, predictions are **anchored to the observed MMR** at the user's "
    "baseline lever settings. The model computes a structural log(MMR) score from the indicators; "
    "the difference between scenario and baseline scores is applied relative to the observed MMR "
    "on the original scale. Thus, when default sliders match the latest data year, predicted MMR "
    "equals the observed reference. When the user increases **ANC4** or **government health "
    "spending**, the risk-oriented score decreases and projected MMR **decreases**; reversing "
    "the lever moves MMR in the opposite direction. **Bootstrap resampling** (120 replicate "
    "fits) provides approximate 95% intervals around the mean trajectory; intervals reflect "
    "model and sampling uncertainty, not full structural or causal uncertainty.",
    "The **time and projections module** extends the same rules through **2030**. Users set "
    "**annual changes** (Δ per year) for each lever; the application linearly projects indicator "
    "values year by year with plausible bounds, then re-computes anchored MMR for each year. "
    "Positive annual Δ on protective indicators (e.g. +1.0 percentage point per year on ANC4, "
    "+0.05 percentage points per year on government health expenditure) therefore trace **downward** "
    "MMR paths when other levers are held constant. Charts show both the MMR trajectory with "
    "uncertainty bands and optional plots of underlying driver variables so users can see how "
    "inputs and outcomes evolve together.",
    "**Preset packages** (e.g. higher skilled birth attendance combined with ANC, contraception, "
    "literacy, and lower fertility or poverty) illustrate multi-domain investment scenarios. "
    "Exports include Excel workbooks for the current scenario snapshot and for year-by-year "
    "projections. Model diagnostics (training rows, countries, in-sample R² and MAE, direction "
    "mapping, calibration parameters) are saved in `models/model_metrics.json` after running "
    "`python scripts/train_model.py`.",
    "Results must be interpreted with explicit **limitations**. The model is a **country-year "
    "associative** specification; coefficients do not identify causal effects of programmes, "
    "and collinearity among development indicators remains. Synthetic inputs demonstrate domains "
    "where APIs are incomplete. Calibration improves responsiveness for planning exercises but "
    "is not a substitute for epidemiological modelling or impact evaluation. For operational "
    "decisions, countries should triangulate with national MDSR, HMIS, DHS/MICS, and budget "
    "analyses. The platform's value is to make **directionally consistent**, transparent "
    "scenario exploration across domains—not to forecast exact MMR levels for accountability "
    "targets without national validation.",
)


def methods_markdown() -> str:
    return "\n\n".join(METHODS_PARAGRAPHS)
